### ISSUE TITLE
default value in commonMain expect fun

### ISSUE THREAD

**Issue by cl3m** [avdim/compose_mpp_workaround#3]
Hi,

your workaround is great but it does not works with expect/actual fun and default value. It crash with these error :

at compilation sometimes:
`java.lang.IllegalStateException: 2. expected value parameter count to be higher: composeFail(
)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.withComposerParamIfNeeded(ComposerParamTransformer.kt:226)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer$copyWithComposerParam$$inlined$also$lambda$1.visitCall(ComposerParamTransformer.kt:584)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:199)
	at org`

at runtime sometimes:
`java.lang.NoSuchMethodError: No static method composeFail(Ljava/lang/String;Landroidx/compose/runtime/Composer;II)V in class Llib/compose/MppKt; or its super classes (declaration of 'lib.compose.MppKt' appears in /data/data/com.sample.compose/code_cache/.overlay/base.apk/classes2.dex)
        at lib.compose.UseComposeActivity$onCreate$1.invoke(UseComposeActivity.kt:18)
        at lib.compose.UseComposeActivity$onCreate$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)`

I've made a example at https://github.com/cl3m/compose_mpp_workaround

The workaround is applied only on the android side. Is there a way to make it work with expect default value ?

Thanks

**Comment by cl3m** [comment]
I've found how to allows default parameter in actual function using @Suppress("ACTUAL_FUNCTION_WITH_DEFAULT_ARGUMENTS"). You can check the repo.
